; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

StatusBaseText := "Press 'Activate' to run programm..."

Gui Main: New, +LabelMain +hWndhMainWnd -MaximizeBox

Gui Add, Button, hWndbtnActivate vBtnActivate gBtnActivate x147 y8 w80 h30, &Activate
Gui Add, Button, hWndbtnDeActivate vBtnDeActivate gBtnDeActivate x147 y48 w80 h30 Disabled , &De-Activate

Gui Add, CheckBox, vAutoPlay gAutoPlay x25 y8 w120 h30 Checked , Auto

Gui Add, StatusBar,, %StatusBaseText%

Gui Show, w269 h131, RSL AutoClicker

Return

F1::
;showTrayTip("Hello, my name is tooltip")
return

AutoPlay:
Gui,Submit,NoHide
return

BtnDeActivate:
BreakLoop = 1
GuiControl, Enable, BtnActivate
GuiControl, Disable, BtnDeActivate
return

BtnActivate:
GuiControlGet, AutoPlay
if !AutoPlay {
    MsgBox,,Info, Mark Checkbox for Autoplay to Activate Tool
    return
}
    
GuiControl, Disable, BtnActivateGuiControl, Enable, BtnDeActivate

loop
{
    if (BreakLoop == 1) {
        SB_SetText(StatusBaseText)
        BreakLoop = 0
        break
    }
    
    if WinActive("ahk_exe Raid.exe"){
        
        if roundEnd() {
            if hasItemToSell(){
                if (!sellItem()){
                    showTrayTip("Item could not be sold. Abort loop.")
                    break
                }
                    
                nextRound()
            }else{
                nextRound()
            } 
        }
    }
    
    SB_SetText("Running!")
    
sleep, 2000
}

Return

;FUNCTIONS

nextRound() {
    ControlSend, , r, ahk_exe Raid.exe
    ;ToolTip, sending 'R' to window
}

imageScanner(section="items", doClick=true, delay=0){

    Loop, Files, images\%section%\*.png 
    {
        ImageSearch x, y, 0, 0, A_ScreenWidth, A_ScreenHeight, %A_LoopFilePath%
           
        if(x && y){
            if(doClick)
                MouseClick, Left, x+30, y+30
                
            if(delay)
                sleep, delay
                
            return true
        }
    }
    return false     
}

roundEnd(){
    return imageScanner("replay", false)
}

hasItemToSell(){
    return imageScanner("items", false)
}

sellItem(delayTime=1000){
    CoordMode Pixel
    
    imageScanner("items", true, delayTime)
    
    imageScanner("coins", true, delayTime)
    
    imageScanner("coins", true, delayTime)

    return true
}


openRaidWindow(){
    WinGetActiveTitle, Title
    WinActivate, ahk_exe Raid.exe
}

showTrayTip(tipText, delay=2000){
    TrayTip, Message, % tipText, % delay
}

MainEscape:
MainClose:
    ExitApp
